routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('register', 'RegisterSiswaController@index')->name('register.index');
Route::post('register/store', 'RegisterSiswaController@store')->name('register.store');
Route::post('orangtua/login', 'OrangtuaLoginController@login')->name('orangtua.login');

Route::prefix('ortu')->middleware(['auth:orangtua'])->group(function(){
    Route::get('dashboard', 'DashboardController@indexOrtu')->name('ortu.dashboard');
    Route::get('jenis-pembayaran', 'PembayaranController@jenisPembayaran')->name('ortu.jenis-pembayaran');
    Route::get('pembayaran', 'PembayaranController@indexOrtu')->name('ortu.pembayaran');
    Route::post('pembayaran/store', 'PembayaranController@store')->name('ortu.pembayaran.store');
    Route::get('riwayat-pembayaran', 'PembayaranController@riwayatPembayaran')->name('ortu.riwayat-pembayaran');
    Route::get('kritik-saran', 'KritikSaranController@create')->name('ortu.kritik-saran');
    Route::post('kritik-saran', 'KritikSaranController@store')->name('ortu.kritik-saran.store');
    Route::get('pembelajaran', 'PembelajaranController@index')->name('ortu.pembelajaran');
    Route::get('pembelajaran/{siswa_id}/{kelas_id}', 'PembelajaranController@show')->name('ortu.pembelajaran.show');

    Route::get('pendaftaran', 'SiswaController@daftarBaru')->name('ortu.daftar-baru');
    Route::post('pendaftaran/store', 'SiswaController@simpanDaftar')->name('ortu.daftar-baru.store');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ortu.ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ortu.ubah_password.change');
});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::middleware(['auth'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sentra', 'SentraController');
    Route::resource('kelas', 'KelasController');
    Route::resource('kegiatan', 'KegiatanController');
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('user', 'UserController')->middleware('admin-only');
    Route::resource('siswa', 'SiswaController');
    Route::resource('kelas-siswa', 'KelasSiswaController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('jadwal/detail/{kelas_id}/{tanggal}', 'JadwalController@jadwalHarian')->name('jadwal.detail_hari');
    Route::get('jadwal/kelas/{kelas_id}/', 'JadwalController@showJadwalKelas')->name('jadwal.kelas');
    Route::get('nilai/{siswa_id}/kelas/{kelas_id}', 'NilaiController@index')->name('nilai.index');
    Route::get('nilai/modal/{siswa_id}/{kelas_id}', 'NilaiController@create')->name('nilai.create');
    Route::post('nilai/store/{siswa_id}/{kelas_id}', 'NilaiController@store')->name('nilai.store');
    Route::get('nilai/{nilai_id}/edit', 'NilaiController@edit')->name('nilai.edit');
    Route::put('nilai/{nilai_id}/edit', 'NilaiController@update')->name('nilai.update');
    Route::delete('nilai/{id}/delete', 'NilaiController@delete')->name('nilai.destroy');
    Route::resource('jenis-pembayaran', 'JenisPembayaranController');
    Route::get('pembayaran', 'PembayaranController@index')->name('pembayaran.index');
    Route::get('pembayaran/{id}/change/{status}', 'PembayaranController@changeStatus')->name('pembayaran.change_status');
    Route::get('kritik-saran', 'KritikSaranController@index')->name('kritik-saran.index');
    Route::post('siswa-status/{siswa_id}', 'SiswaController@changeStatus')->name('siswa.changeStatus');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ubah_password.change');
});

app/Siswa.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $table = 'siswa';

    protected $fillable = [
        'nama_lengkap',
        'tempat_lahir',
        'tanggal_lahir',
        'jenis_kelamin',
        'status',
        'orangtua_id',
        'keterangan'
    ];

    protected $status_text = [
        '0' => 'Pending',
        '1' => 'Diterima',
        '2' => 'Aktif',
        '3' => 'Lulus A',
        '4' => 'Lulus B',
        '5' => 'Gagal',
        '6' => 'Ditolak',
    ];

    public static function getDefaultValues($type = null)
    {
        if($type == null){
            return (object) [
                'nama_lengkap' => '',
                'tempat_lahir' => '',
                'tanggal_lahir' => '',
                'jenis_kelamin' => '',
                'status' => '',
                'orangtua_id' => ''
            ];
        } else {
            return (object) [
                'nama_lengkap_anak' => '',
                'tempat_lahir' => '',
                'tanggal_lahir' => '',
                'jenis_kelamin' => '',
                'status' => '',
                'orangtua_id' => ''
            ];
        }
    }

    public function orangtua()
    {
        return $this->belongsTo('App\Orangtua');
    }

    public function getJenisKelamin()
    {
        if($this->jenis_kelamin == 'l'){
            return 'Laki - laki';
        } else {
            return 'Perempuan';
        }
    }

    public function getStatus()
    {
        return $this->status_text[$this->status];
    }

    public function getStatusBadge()
    {
        if($this->status == 0){
            return "<span class='badge badge-warning'>".$this->status_text[$this->status]."</span>";
        }
        if($this->status == 1){
            return "<span class='badge badge-info'>".$this->status_text[$this->status]."</span>";
        }
        if($this->status == 2){
            return "<span class='badge badge-primary'>".$this->status_text[$this->status]."</span>";
        }
        if($this->status == 3){
            return "<span class='badge badge-success'>".$this->status_text[$this->status]."</span>";
        }
        if($this->status == 4){
            return "<span class='badge badge-success'>".$this->status_text[$this->status]."</span>";
        }
        if($this->status == 5){
            return "<span class='badge badge-danger'>".$this->status_text[$this->status]."</span>";
        }
        if($this->status == 6){
            return "<span class='badge badge-danger'>".$this->status_text[$this->status]."</span>";
        }
    }

    public function getAge()
    {
        return Carbon::parse($this->attributes['tanggal_lahir'])->age;
    }

    public function kelasSiswa()
    {
        return $this->belongsToMany('App\Kelas')->withTimestamps();
    }

}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Orangtua;
use App\Siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['siswa'] = Siswa::orderBy('nama_lengkap', 'asc')->get();
        return view('admin.siswa.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['siswa'] = Siswa::getDefaultValues();
        $data['orangtua'] = Orangtua::orderBy('nama_lengkap')->get();
        return view('admin.siswa.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'orangtua_id' => 'required'
        ]);
        $request['status'] = '1';

        Siswa::create($request->toArray());
        return redirect()->route('siswa.index')->with('success', 'Berhasil menambah data siswa');
    }
    
    public function changeStatus(Request $request, $siswa_id)
    {
        $input = $request->toArray();

        if($input['status'] == 3 || $input['status'] == 4){
            $text = 'menyatakan lulus';
        } else if($input['status'] == 2) {
            $text = 'menyatakan aktif';
        } else {
            $text = 'menyatakan tidak lulus';
        }

        Siswa::find($siswa_id)->update(['status' => $input['status']]);

        return redirect()->back()->with('success', 'Berhasil ' . $text . ' siswa ini');
    }


    
    public function daftarBaru()
    {
        return view('orangtua.daftar_baru');
    }

    public function simpanDaftar(Request $request)
    {
        $request->validate([
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'tahun_ajar' => 'required',
        ]);

        $input = $request->toArray();

        $input['orangtua_id'] = Auth::guard('orangtua')->user()->id;

        $input['status'] = 0;

        $input['keterangan'] = 'Didaftarkan pada kelompok: '.  ucwords($request->jenis_kelompok) . ', tahun ajar ' .$request->tahun_ajar;

        Siswa::create($input);

        return redirect()->back()->with('success', 'Berhasil mendaftarkan anak. Sekarang silahkan lengkapi pembayaran pada menu pembayaran agar pendaftaran diterima dan dikonfirmasi oleh petugas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $siswa = Siswa::find($id);
        return view('admin.siswa.modal', compact('siswa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['siswa'] = Siswa::find($id);
        $data['orangtua'] = Orangtua::orderBy('nama_lengkap')->get();
        return view('admin.siswa.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'orangtua_id' => 'required'
        ]);
        
        $siswa = Siswa::find($id);

        $siswa->update($request->all());

        return redirect()->route('siswa.index')->with('success', 'Berhasil mengubah data siswa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = Siswa::find($id);

        $siswa->delete();

        return redirect()->route('siswa.index')->with('success', 'Berhasil menghapus data siswa');
    }
}

resources/views/admin/siswa/form.blade.php
@extends('layouts.app')

@section('title', 'Form Siswa')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="card">
                <div class="card-header">
                    Form Siswa
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($siswa->id)) ?  route('siswa.store') : route('siswa.update', $siswa->id) }}" method="post">
                        @csrf
        
                        @if(isset($siswa->id))
                            @method('put')
                        @endif

                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">                            
                                <label>Orangtua</label>
                                <select name="orangtua_id" class="form-control mySelect">
                                    <option value=""> - Pilih orangtua -</option>
                                    @foreach($orangtua as $option)
                                        <option value="{{ $option->id }}" {{ (old('orangtua_id') == $option->id || $siswa->orangtua_id == $option->id) ? 'selected' : '' }}>{{ ucwords($option->nama_lengkap) }}</option>
                                    @endforeach
                                </select>
                                @error('orangtua_id')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror                           
                            </div>
                        </div> 
        
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Nama lengkap</label>
                                <input type="text" class="form-control form-control-user" name="nama_lengkap" value="{{ old('nama_lengkap', $siswa->nama_lengkap) }}">
                                @error('nama_lengkap')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>                        

                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <label>Tempat Lahir</label>
                                <input type="text" class="form-control form-control-user" name="tempat_lahir" value="{{ old('tempat_lahir', $siswa->tempat_lahir) }}">
                                @error('tempat_lahir')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-sm-6 mb-2">
                                <label>Tanggal Lahir</label>
                                <input type="text" class="form-control form-control-user datepicker" name="tanggal_lahir" value="{{ old('tanggal_lahir', $siswa->tanggal_lahir) }}">
                                @error('tanggal_lahir')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                       
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">                            
                                <label>Jenis Kelamin</label>
                                <select name="jenis_kelamin" class="form-control">
                                    <option value=""> - Pilih Jenis Kelamin -</option>
                                    <option value="l" {{ (old('jenis_kelamin') == 'l' || $siswa->jenis_kelamin == 'l') ? 'selected' : '' }}>Laki - Laki</option>
                                    <option value="p" {{ (old('jenis_kelamin') == 'p' || $siswa->jenis_kelamin == 'p') ? 'selected' : '' }}>Perempuan</option>                                    
                                </select>
                                @error('jenis_kelamin')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror                           
                            </div>
                        </div>                                                                
                        
                        <button type="submit" class="btn btn-warning btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Simpan</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/siswa/index.blade.php
@extends('layouts.app')

@section('title', 'Siswa')

@section('content')

<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header font-weight-bold text-primary">
                    Data Master Siswa
                </div>
                <div class="card-body">
                    <a href="{{ route('siswa.create') }}" class="btn btn-warning mb-4 btn-sm"><i class="fa fa-plus"></i> Tambah</a>

                    <table class="table table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama</th>
                                <th>TTL</th>
                                <th>Umur</th>
                                <th>J. Kel</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($siswa as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_lengkap }}</td>
                                <td>{{ $row->tempat_lahir . ', ' . $row->tanggal_lahir }}</td>
                                <td>{!! $row->getAge() !!} Thn</td>
                                <td>{{ $row->getJenisKelamin() }}</td>
                                <td>{!! $row->getStatusBadge() !!}</td>
                                <td>
                                    <form action="{{ route('siswa.destroy', $row->id) }}" method="post">
                                        <a href="{{ route('siswa.show', $row->id) }}" class="btn btn-sm btn-info btn-show" title="Detail Siswa"><i class="fa fa-eye"></i></a>
                                        <a href="{{ route('siswa.edit', $row->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-cog"></i></a>
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin hapus data?')" >
                                            <span class="icon text-white">
                                            <i class="fas fa-trash"></i>
                                            </span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="theModal" class="modal fade text-center">
    <div class="modal-dialog modal-lg">
        <div class="modal-content modal-lg">
        </div>
    </div>
</div>



@endsection


@push('scripts')

<script>
    $('.btn-show').on('click', function(e){
        e.preventDefault();
        $('#theModal').modal('show').find('.modal-content').load($(this).attr('href'));
    });
</script>

@endpush

resources/views/admin/siswa/modal.blade.php
<div class="modal-header">
    <h5 class="modal-title">Detail Siswa</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <table class="table text-left">
                <tr>
                    <th style="border-top:0">Nama Siswa</th>
                    <td style="border-top:0">:</td>
                    <td style="border-top:0">{{ $siswa->nama_lengkap }}</td>
                </tr>
                <tr>
                    <th>Tempat, Tanggal Lahir</th>
                    <td>:</td>
                    <td>{{ $siswa->tempat_lahir . ', ' . $siswa->tanggal_lahir }}</td>
                </tr>
                <tr>
                    <th>Umur</th>
                    <td>:</td>
                    <td>{!! $siswa->getAge() !!} Thn</td>
                </tr>
                <tr>
                    <th>Jenis Kelamin</th>
                    <td>:</td>
                    <td>{{ $siswa->getJenisKelamin() }}</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>:</td>
                    <td>{!! $siswa->getStatusBadge() !!}</td>
                </tr>
                <tr>
                    <th>Keterangan</th>
                    <td>:</td>
                    <td>{{ $siswa->keterangan }}</td>
                </tr>
                <tr>
                    <th>Orangtua</th>
                    <td>:</td>
                    <td>{{ $siswa->orangtua->nama_lengkap }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>