routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('register', 'RegisterSiswaController@index')->name('register.index');
Route::post('register/store', 'RegisterSiswaController@store')->name('register.store');
Route::post('orangtua/login', 'OrangtuaLoginController@login')->name('orangtua.login');

Route::prefix('ortu')->middleware(['auth:orangtua'])->group(function(){
    Route::get('dashboard', 'DashboardController@indexOrtu')->name('ortu.dashboard');
    Route::get('jenis-pembayaran', 'PembayaranController@jenisPembayaran')->name('ortu.jenis-pembayaran');
    Route::get('pembayaran', 'PembayaranController@indexOrtu')->name('ortu.pembayaran');
    Route::post('pembayaran/store', 'PembayaranController@store')->name('ortu.pembayaran.store');
    Route::get('riwayat-pembayaran', 'PembayaranController@riwayatPembayaran')->name('ortu.riwayat-pembayaran');
    Route::get('kritik-saran', 'KritikSaranController@create')->name('ortu.kritik-saran');
    Route::post('kritik-saran', 'KritikSaranController@store')->name('ortu.kritik-saran.store');
    Route::get('pembelajaran', 'PembelajaranController@index')->name('ortu.pembelajaran');
    Route::get('pembelajaran/{siswa_id}/{kelas_id}', 'PembelajaranController@show')->name('ortu.pembelajaran.show');

    Route::get('pendaftaran', 'SiswaController@daftarBaru')->name('ortu.daftar-baru');
    Route::post('pendaftaran/store', 'SiswaController@simpanDaftar')->name('ortu.daftar-baru.store');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ortu.ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ortu.ubah_password.change');
});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::middleware(['auth'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sentra', 'SentraController');
    Route::resource('kelas', 'KelasController');
    Route::resource('kegiatan', 'KegiatanController');
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('user', 'UserController')->middleware('admin-only');
    Route::resource('siswa', 'SiswaController');
    Route::resource('kelas-siswa', 'KelasSiswaController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('jadwal/detail/{kelas_id}/{tanggal}', 'JadwalController@jadwalHarian')->name('jadwal.detail_hari');
    Route::get('jadwal/kelas/{kelas_id}/', 'JadwalController@showJadwalKelas')->name('jadwal.kelas');
    Route::get('nilai/{siswa_id}/kelas/{kelas_id}', 'NilaiController@index')->name('nilai.index');
    Route::get('nilai/modal/{siswa_id}/{kelas_id}', 'NilaiController@create')->name('nilai.create');
    Route::post('nilai/store/{siswa_id}/{kelas_id}', 'NilaiController@store')->name('nilai.store');
    Route::get('nilai/{nilai_id}/edit', 'NilaiController@edit')->name('nilai.edit');
    Route::put('nilai/{nilai_id}/edit', 'NilaiController@update')->name('nilai.update');
    Route::delete('nilai/{id}/delete', 'NilaiController@delete')->name('nilai.destroy');
    Route::resource('jenis-pembayaran', 'JenisPembayaranController');
    Route::get('pembayaran', 'PembayaranController@index')->name('pembayaran.index');
    Route::get('pembayaran/{id}/change/{status}', 'PembayaranController@changeStatus')->name('pembayaran.change_status');
    Route::get('kritik-saran', 'KritikSaranController@index')->name('kritik-saran.index');
    Route::post('siswa-status/{siswa_id}', 'SiswaController@changeStatus')->name('siswa.changeStatus');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ubah_password.change');
});

app/Sentra.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sentra extends Model
{
    protected $table = 'Sentra';

    protected $fillable = [
        'nama_sentra',
        'keterangan',
    ];

    public static function getDefaultValues()
    {
        return (object) [
            'nama_sentra' => '',
            'keterangan' => ''
        ];
    }

    public function kegiatan()
    {
        return $this->hasMany('App\Kegiatan');
    }
}

app/Http/Controllers/SentraController.php
<?php

namespace App\Http\Controllers;

use App\Sentra;
use Illuminate\Http\Request;

class SentraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['sentra'] = Sentra::orderBy('nama_sentra', 'asc')->get();
        return view('admin.sentra.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['sentra'] = Sentra::getDefaultValues();
        return view('admin.sentra.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_sentra' => 'required',
        ]);
        Sentra::create($request->all());
        return redirect()->route('sentra.index')->with('success', 'Berhasil menambah data sentra');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sentra = Sentra::find($id);
        return view('admin.sentra.form', compact('sentra'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_sentra' => 'required'
        ]);
        
        $sentra = Sentra::find($id);

        $sentra->update($request->all());

        return redirect()->route('sentra.index')->with('success', 'Berhasil mengubah data sentra');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sentra = Sentra::find($id);

        $sentra->delete();

        return redirect()->route('sentra.index')->with('success', 'Berhasil menghapus data sentra');
    }
}

resources/views/admin/sentra/form.blade.php
@extends('layouts.app')

@section('title', 'Form Sentra')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="card">
                <div class="card-header">
                    Form Sentra
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($sentra->id)) ?  route('sentra.store') : route('sentra.update', $sentra->id) }}" method="post">
                        @csrf
        
                        @if(isset($sentra->id))
                            @method('put')
                        @endif
        
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Nama Sentra</label>
                                <input type="text" class="form-control form-control-user" name="nama_sentra" value="{{ old('nama_sentra', $sentra->nama_sentra) }}">
                                @error('nama_sentra')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Keterangan</label>
                                <textarea class="form-control form-control-user" name="keterangan">{{ old('keterangan', $sentra->keterangan) }}</textarea>
                                @error('keterangan')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        
                        <button type="submit" class="btn btn-warning btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Simpan</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/sentra/index.blade.php
@extends('layouts.app')

@section('title', 'Sentra')

@section('content')

<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header font-weight-bold text-primary">
                    Data Master Sentra
                </div>
                <div class="card-body">
                    <a href="{{ route('sentra.create') }}" class="btn btn-warning mb-4 btn-sm"><i class="fa fa-plus"></i> Tambah</a>

                    <table class="table table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama Sentra</th>
                                <th>Keterangan</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($sentra as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_sentra }}</td>
                                <td>{{ $row->keterangan }}</td>
                                <td>
                                    <form action="{{ route('sentra.destroy', $row->id) }}" method="post">                                       
                                        <a href="{{ route('sentra.edit', $row->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-cog"></i></a>
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin hapus data?')" >
                                            <span class="icon text-white">
                                            <i class="fas fa-trash"></i>
                                            </span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection