routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('register', 'RegisterSiswaController@index')->name('register.index');
Route::post('register/store', 'RegisterSiswaController@store')->name('register.store');
Route::post('orangtua/login', 'OrangtuaLoginController@login')->name('orangtua.login');

Route::prefix('ortu')->middleware(['auth:orangtua'])->group(function(){
    Route::get('dashboard', 'DashboardController@indexOrtu')->name('ortu.dashboard');
    Route::get('jenis-pembayaran', 'PembayaranController@jenisPembayaran')->name('ortu.jenis-pembayaran');
    Route::get('pembayaran', 'PembayaranController@indexOrtu')->name('ortu.pembayaran');
    Route::post('pembayaran/store', 'PembayaranController@store')->name('ortu.pembayaran.store');
    Route::get('riwayat-pembayaran', 'PembayaranController@riwayatPembayaran')->name('ortu.riwayat-pembayaran');
    Route::get('kritik-saran', 'KritikSaranController@create')->name('ortu.kritik-saran');
    Route::post('kritik-saran', 'KritikSaranController@store')->name('ortu.kritik-saran.store');
    Route::get('pembelajaran', 'PembelajaranController@index')->name('ortu.pembelajaran');
    Route::get('pembelajaran/{siswa_id}/{kelas_id}', 'PembelajaranController@show')->name('ortu.pembelajaran.show');

    Route::get('pendaftaran', 'SiswaController@daftarBaru')->name('ortu.daftar-baru');
    Route::post('pendaftaran/store', 'SiswaController@simpanDaftar')->name('ortu.daftar-baru.store');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ortu.ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ortu.ubah_password.change');
});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::middleware(['auth'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sentra', 'SentraController');
    Route::resource('kelas', 'KelasController');
    Route::resource('kegiatan', 'KegiatanController');
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('user', 'UserController')->middleware('admin-only');
    Route::resource('siswa', 'SiswaController');
    Route::resource('kelas-siswa', 'KelasSiswaController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('jadwal/detail/{kelas_id}/{tanggal}', 'JadwalController@jadwalHarian')->name('jadwal.detail_hari');
    Route::get('jadwal/kelas/{kelas_id}/', 'JadwalController@showJadwalKelas')->name('jadwal.kelas');
    Route::get('nilai/{siswa_id}/kelas/{kelas_id}', 'NilaiController@index')->name('nilai.index');
    Route::get('nilai/modal/{siswa_id}/{kelas_id}', 'NilaiController@create')->name('nilai.create');
    Route::post('nilai/store/{siswa_id}/{kelas_id}', 'NilaiController@store')->name('nilai.store');
    Route::get('nilai/{nilai_id}/edit', 'NilaiController@edit')->name('nilai.edit');
    Route::put('nilai/{nilai_id}/edit', 'NilaiController@update')->name('nilai.update');
    Route::delete('nilai/{id}/delete', 'NilaiController@delete')->name('nilai.destroy');
    Route::resource('jenis-pembayaran', 'JenisPembayaranController');
    Route::get('pembayaran', 'PembayaranController@index')->name('pembayaran.index');
    Route::get('pembayaran/{id}/change/{status}', 'PembayaranController@changeStatus')->name('pembayaran.change_status');
    Route::get('kritik-saran', 'KritikSaranController@index')->name('kritik-saran.index');
    Route::post('siswa-status/{siswa_id}', 'SiswaController@changeStatus')->name('siswa.changeStatus');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ubah_password.change');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title') - PAUD Anak Emas</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('css/sb-admin-2.css')}}" rel="stylesheet">

    <link href="{{ asset('css/additional.css')}}" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Select2js -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />

</head>
<!-- Login Form if not authenticated -->
@guest 
  @yield('content')
@endguest

@auth
<body id="page-top" class="custom-bg">

    <!-- Page Wrapper -->
    <div id="wrapper">
  
      <!-- Sidebar -->
      @include('layouts.sidebar')
      <!-- End of Sidebar -->
  
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
  
        <!-- Main Content -->
        <div id="content">
  
            <!-- Topbar -->
            @include('layouts.topbar')
            <!-- End of Topbar -->
  
            <!-- Begin Page Content -->
            @include('layouts.flash')

            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">@yield('title')</h1>
                </div>
            </div>

            @yield('content')
            
            <!-- /.container-fluid -->
  
        </div>
        <!-- End of Main Content -->
  
        <!-- Footer -->
        @include('layouts.footer')
        <!-- End of Footer -->
  
      </div>
      <!-- End of Content Wrapper -->
  
    </div>
    <!-- End of Page Wrapper -->
  
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  
    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $( function() {
      $( ".datepicker" ).datepicker({ 
        dateFormat: 'yy-mm-dd',
        changeYear: true,
        changeMonth: true,
        yearRange: "1950:2020"
      });
    } );
    </script>
  
    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>


    <script>
      $(document).ready( function () {
          $('#myTable').DataTable();
          
          //select2 input option
          $('.mySelect').select2();
      } );
    </script>

    @stack('scripts')

  </body>
  @endauth
  
  </html>        

resources/views/layouts/flash.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">            
            @if(session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show my-toast" role="alert">
                <strong>Success!</strong> {{ session()->get('success') }}.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif

            @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible fade show my-toast" role="alert">
                <strong>Error!</strong> {{ session()->get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span class="fa fa-times"></span>
                </button>
            </div>
            @endif

            @if(session()->has('warning'))
            <div class="alert alert-warning alert-dismissible fade show my-toast" role="alert">
                <strong>Warning!</strong> {{ session()->get('warning') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span class="fa fa-times"></span>
                </button>
            </div>
            @endif         
        </div>
    </div>
</div>

resources/views/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; 2020 PAUD Anak Emas.</span>
        </div>
    </div>
</footer>

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav custom-bg-gradient sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('dashboard')}}">
        <div class="sidebar-brand-icon">
            <i class="fa fa-child"></i>
          </div>
        <div class="sidebar-brand-text mx-3">PAUD Anak Emas</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    @if(Auth::guard('web')->check())
        <!-- Nav Item - Dashboard -->
        <li class="nav-item {{ (urlHasPrefix('dashboard') == true ) ? 'active' : '' }}">
            <a class="nav-link" href="{{ url('dashboard') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <hr class="sidebar-divider">
        <div class="sidebar-heading">
            Master
        </div>
        <li class="nav-item {{ (urlHasPrefix('sentra') == true ) ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('sentra.index') }}">
                <i class="fas fa-comments"></i>
                <span>Sentra</span>
            </a>        
        </li>

        <li class="nav-item {{ (urlHasPrefix('kelas') == true ) ? 'active' : '' }} sidebar-link">
            <a class="nav-link" href="{{ route('kelas.index') }}">
                <i class="fas fa-school"></i>
                <span>Kelas</span>
            </a>        
        </li>

        <li class="nav-item {{ (urlHasPrefix('kegiatan') == true ) ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('kegiatan.index') }}">
                <i class="fas fa-list-alt"></i>
                <span>Kegiatan / Pelajaran</span>
            </a>        
        </li>

        <li class="nav-item {{ (urlHasPrefix('orangtua') == true ) ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('orangtua.index') }}">
                <i class="fas fa-user-tie"></i>
                <span>Orangtua</span>
            </a>
        </li>

        <li class="nav-item {{ (urlHasPrefix('siswa') == true ) ? 'active' : '' }} sidebar-link">
            <a class="nav-link" href="{{ route('siswa.index') }}">
                <i class="fas fa-child"></i>
                <span>Siswa</span>
            </a>
        </li>
        @if(Auth::guard('web')->user()->level == 2)
        <li class="nav-item {{ (urlHasPrefix('user') == true ) ? 'active' : '' }} sidebar-link">
            <a class="nav-link" href="{{ route('user.index') }}">
                <i class="fas fa-user"></i>
                <span>Admin / Guru</span>
            </a>
        </li>
        @endif
        
        <li class="nav-item {{ (urlHasPrefix('jenis-pembayaran') == true ) ? 'active' : '' }} sidebar-link">
            <a class="nav-link" href="{{ route('jenis-pembayaran.index') }}">
                <i class="fas fa-dollar-sign"></i>
                <span>Jenis Pembayaran</span>
            </a>
        </li>

        <hr class="sidebar-divider">
        <div class="sidebar-heading">
            Aktifitas
        </div>
        <li class="nav-item {{ (urlHasPrefix('kelas-siswa') == true ) ? 'active' : '' }} sidebar-pembelajaran">
            <a class="nav-link" href="{{ route('kelas-siswa.index') }}">
                <i class="fas fa-swatchbook"></i>
                <span>Pembelajaran</span>
            </a>
        </li>

        <li class="nav-item {{ (urlHasPrefix('pembayaran') == true ) ? 'active' : '' }} sidebar-whatever">
            <a class="nav-link" href="{{ route('pembayaran.index') }}">
                <i class="fas fa-money-check"></i>
                <span>Pembayaran</span>
            </a>
        </li>
        @if(Auth::guard('web')->user()->level == 2)
        <hr class="sidebar-divider">
        <div class="sidebar-heading">
            Extra
        </div>
        <li class="nav-item {{ (urlHasPrefix('kritik-saran') == true ) ? 'active' : '' }} sidebar-link">
            <a class="nav-link" href="{{ route('kritik-saran.index') }}">
                <i class="fas fa-clipboard"></i>
                <span>Kritik & Saran</span>
            </a>
        </li>
        @endif

    @endif

    @if(Auth::guard('orangtua')->check())
    <li class="nav-item {{ (urlHasPrefix('dashboard') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ url('ortu/dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Aktifitas
    </div>
    <li class="nav-item {{ (urlHasPrefix('pembelajaran') == true ) ? 'active' : '' }} sidebar-pembelajaran">
        <a class="nav-link" href="{{ route('ortu.pembelajaran') }}">
            <i class="fas fa-swatchbook"></i>
            <span>Pembelajaran</span>
        </a>
    </li>

    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Menu Pembayaran
    </div>
    <li class="nav-item {{ (urlHasPrefix('jenis-pembayaran') == true ) ? 'active' : '' }} sidebar-link">
        <a class="nav-link" href="{{ route('ortu.jenis-pembayaran') }}">
            <i class="fas fa-dollar-sign"></i>
            <span>Jenis Pembayaran</span>
        </a>
    </li>
    <li class="nav-item {{ (urlHasPrefix('pembayaran') == true ) ? 'active' : '' }} sidebar-pembayaran">
        <a class="nav-link" href="{{ route('ortu.pembayaran') }}">
            <i class="fas fa-money-check-alt"></i>
            <span>Pembayaran</span>
        </a>
    </li>

    <li class="nav-item {{ (urlHasPrefix('riwayat-pembayaran') == true ) ? 'active' : '' }} sidebar-riwayat">
        <a class="nav-link" href="{{ route('ortu.riwayat-pembayaran') }}">
            <i class="fas fa-history"></i>
            <span>Riwayat Pembayaran</span>
        </a>
    </li>

    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Extra
    </div>
    <li class="nav-item {{ (urlHasPrefix('kritik-saran') == true ) ? 'active' : '' }} sidebar-link">
        <a class="nav-link" href="{{ route('ortu.kritik-saran') }}">
            <i class="fas fa-clipboard"></i>
            <span>Kritik & Saran</span>
        </a>
    </li>
    <li class="nav-item {{ (urlHasPrefix('daftar-baru') == true ) ? 'active' : '' }} sidebar-link">
        <a class="nav-link" href="{{ route('ortu.daftar-baru') }}">
            <i class="fas fa-user-plus"></i>
            <span>Daftar Anak Lain</span>
        </a>
    </li>
    @endif
    

    
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

resources/views/layouts/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                    @if(Auth::guard('web')->check())
                    {{ Auth::guard('web')->user()->username }}
                    @else 
                    {{ Auth::guard('orangtua')->user()->username }}
                    @endif
                </span>               
                <img class="img-profile rounded-circle" src="{{ asset('img/default.png') }}" width="30" alt="img">               
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="@if(Auth::guard('web')->check())
                    {{ route('ubah_password') }}
                    @else 
                    {{ route('ortu.ubah_password') }}
                    @endif">
                    <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                    Ubah Password
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yakin akan logout?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Klik "Logout" dibawah jika anda ingin melakukan logout dari sistem.</div>
            <div class="modal-footer">
                <form action="{{ route('logout') }}" method="post">
                    @csrf
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary" href="">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>