routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('register', 'RegisterSiswaController@index')->name('register.index');
Route::post('register/store', 'RegisterSiswaController@store')->name('register.store');
Route::post('orangtua/login', 'OrangtuaLoginController@login')->name('orangtua.login');

Route::prefix('ortu')->middleware(['auth:orangtua'])->group(function(){
    Route::get('dashboard', 'DashboardController@indexOrtu')->name('ortu.dashboard');
    Route::get('jenis-pembayaran', 'PembayaranController@jenisPembayaran')->name('ortu.jenis-pembayaran');
    Route::get('pembayaran', 'PembayaranController@indexOrtu')->name('ortu.pembayaran');
    Route::post('pembayaran/store', 'PembayaranController@store')->name('ortu.pembayaran.store');
    Route::get('riwayat-pembayaran', 'PembayaranController@riwayatPembayaran')->name('ortu.riwayat-pembayaran');
    Route::get('kritik-saran', 'KritikSaranController@create')->name('ortu.kritik-saran');
    Route::post('kritik-saran', 'KritikSaranController@store')->name('ortu.kritik-saran.store');
    Route::get('pembelajaran', 'PembelajaranController@index')->name('ortu.pembelajaran');
    Route::get('pembelajaran/{siswa_id}/{kelas_id}', 'PembelajaranController@show')->name('ortu.pembelajaran.show');

    Route::get('pendaftaran', 'SiswaController@daftarBaru')->name('ortu.daftar-baru');
    Route::post('pendaftaran/store', 'SiswaController@simpanDaftar')->name('ortu.daftar-baru.store');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ortu.ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ortu.ubah_password.change');
});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::middleware(['auth'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sentra', 'SentraController');
    Route::resource('kelas', 'KelasController');
    Route::resource('kegiatan', 'KegiatanController');
    Route::resource('orangtua', 'OrangtuaController');
    Route::resource('user', 'UserController')->middleware('admin-only');
    Route::resource('siswa', 'SiswaController');
    Route::resource('kelas-siswa', 'KelasSiswaController');
    Route::resource('jadwal', 'JadwalController');
    Route::get('jadwal/detail/{kelas_id}/{tanggal}', 'JadwalController@jadwalHarian')->name('jadwal.detail_hari');
    Route::get('jadwal/kelas/{kelas_id}/', 'JadwalController@showJadwalKelas')->name('jadwal.kelas');
    Route::get('nilai/{siswa_id}/kelas/{kelas_id}', 'NilaiController@index')->name('nilai.index');
    Route::get('nilai/modal/{siswa_id}/{kelas_id}', 'NilaiController@create')->name('nilai.create');
    Route::post('nilai/store/{siswa_id}/{kelas_id}', 'NilaiController@store')->name('nilai.store');
    Route::get('nilai/{nilai_id}/edit', 'NilaiController@edit')->name('nilai.edit');
    Route::put('nilai/{nilai_id}/edit', 'NilaiController@update')->name('nilai.update');
    Route::delete('nilai/{id}/delete', 'NilaiController@delete')->name('nilai.destroy');
    Route::resource('jenis-pembayaran', 'JenisPembayaranController');
    Route::get('pembayaran', 'PembayaranController@index')->name('pembayaran.index');
    Route::get('pembayaran/{id}/change/{status}', 'PembayaranController@changeStatus')->name('pembayaran.change_status');
    Route::get('kritik-saran', 'KritikSaranController@index')->name('kritik-saran.index');
    Route::post('siswa-status/{siswa_id}', 'SiswaController@changeStatus')->name('siswa.changeStatus');

    Route::get('ubah_password', 'UbahPasswordController@index')->name('ubah_password');
    Route::post('ubah_password', 'UbahPasswordController@change')->name('ubah_password.change');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama_lengkap', 'username', 'email', 'password', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'level'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }


    public static function getDefaultValues()
    {
        return (object) [
            'nama_lengkap' => '', 
            'username' => '', 
            'email' => '', 
            'password' => '', 
            'tempat_lahir' => '',
            'tanggal_lahir' => '',
            'jenis_kelamin' => '',
            'level' => ''
        ];
    }

    public function getLevelBadge()
    {
        if($this->level == 1){
            return "<span class='badge badge-success'>Guru</span>";
        } else if($this->level == 2){
            return "<span class='badge badge-primary'>Admin</span>";
        }
    }

    public function getJenisKelamin()
    {
        if($this->jenis_kelamin == 'l'){
            return 'Laki - laki';
        } else {
            return 'Perempuan';
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['user'] = User::orderBy('nama_lengkap', 'asc')->get();
        return view('admin.user.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = User::getDefaultValues();
        return view('admin.user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_lengkap' => 'required',
            'username' => 'required|unique:users',
            'password' => 'required',
            'email' => 'required|unique:users',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'level' => 'required'
        ]);
        User::create($request->all());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('admin.user.modal', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_lengkap' => 'required',
            'username' => 'required|unique:users,username,'.$id,
            'email' => 'required|unique:users,email,'.$id,
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'level' => 'required'
        ]);
        
        $user = User::find($id);

        $user->update($request->all());

        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        $user->delete();

        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data user');
    }
}

resources/views/admin/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form Admin / Guru')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="card">
                <div class="card-header">
                    Form Admin / Guru
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($user->id)) ?  route('user.store') : route('user.update', $user->id) }}" method="post">
                        @csrf
        
                        @if(isset($user->id))
                            @method('put')
                        @endif
        
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Nama lengkap</label>
                                <input type="text" class="form-control form-control-user" name="nama_lengkap" value="{{ old('nama_lengkap', $user->nama_lengkap) }}">
                                @error('nama_lengkap')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Username</label>
                                <input type="text" class="form-control form-control-user" name="username" value="{{ old('username', $user->username) }}">
                                @error('username')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        @if(!isset($user->id))
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Password</label>
                                <input type="password" class="form-control form-control-user" name="password" value="{{ old('password', $user->password) }}">
                                @error('password')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        @endif
                        
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Email</label>
                                <input type="email" class="form-control form-control-user" name="email" value="{{ old('email', $user->email) }}">
                                @error('email')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <label>Tempat Lahir</label>
                                <input type="text" class="form-control form-control-user" name="tempat_lahir" value="{{ old('tempat_lahir', $user->tempat_lahir) }}">
                                @error('tempat_lahir')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-sm-6 mb-2">
                                <label>Tanggal Lahir</label>
                                <input type="text" class="form-control form-control-user datepicker" name="tanggal_lahir" value="{{ old('tanggal_lahir', $user->tanggal_lahir) }}">
                                @error('tanggal_lahir')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <label>Jenis Kelamin</label>
                                <select name="jenis_kelamin" class="form-control">
                                    <option value=""> - Pilih Jenis Kelamin -</option>
                                    <option value="l" {{ (old('jenis_kelamin') == 'l' || $user->jenis_kelamin == 'l') ? 'selected' : '' }}>Laki - Laki</option>
                                    <option value="p" {{ (old('jenis_kelamin') == 'p' || $user->jenis_kelamin == 'p') ? 'selected' : '' }}>Perempuan</option>                                    
                                </select>
                                @error('jenis_kelamin')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="col-sm-6 mb-2">
                                <label>Level</label>
                                <select name="level" class="form-control">
                                    <option value=""> - Pilih Level -</option>
                                    <option value="1" {{ (old('level') == '1' || $user->level == '1') ? 'selected' : '' }}>Guru</option>
                                    <option value="2" {{ (old('level') == '2' || $user->level == '2') ? 'selected' : '' }}>Admin</option>                                    
                                </select>
                                @error('level')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        
                        <button type="submit" class="btn btn-warning btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Simpan</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('title', 'User / Guru')

@section('content')

<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header font-weight-bold text-primary">
                    Data Master Admin / Guru
                </div>
                <div class="card-body">
                    <a href="{{ route('user.create') }}" class="btn btn-warning mb-4 btn-sm"><i class="fa fa-plus"></i> Tambah</a>

                    <table class="table table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama</th>
                                <th>TTL</th>
                                <th>Email</th>
                                <th>J. Kel</th>
                                <th>Level</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($user as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_lengkap }}</td>
                                <td>{{ $row->tempat_lahir . ', ' . $row->tanggal_lahir }}</td>
                                <td>{{ $row->email }}</td>
                                <td>{{ $row->getJenisKelamin() }}</td>
                                <td>{!! $row->getLevelBadge() !!}</td>
                                <td>
                                    <form action="{{ route('user.destroy', $row->id) }}" method="post">

                                        <a href="{{ route('user.edit', $row->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-cog"></i></a>
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin hapus data?')" >
                                            <span class="icon text-white">
                                            <i class="fas fa-trash"></i>
                                            </span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection


@push('scripts')



@endpush